name: CI/CD Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - continuous-integration-setup

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 0r requirements/base.txt -r requirements/test.txt

      - name: Set up Django environment 
        run: |
          echo "export DJANGO_SETTINGS_MODULE=pic_sleuth.config.settings" >> $GITHUB_ENV

      - name: Lint code
        run: flake8

      - name: Run unit tests
        run: pytest

  deploy-on-merge:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

